# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s7mM3oEG7pRo0cICwn20BJ30VjnpnH3D

# **BÀI TẬP CÁ NHÂN (20%)**
## **ĐỀ: Phân tích (hiện trạng) và khuyến nghị AI Agent trong ngành Khoa học máy tính**


---
- Kết quả: Github
- Công cụ: Workbank, Colab, Streamlit
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from scipy.stats import mstats
import warnings
warnings.filterwarnings("ignore", category=FutureWarning)

"""# **1. Data Preprocessing**"""

#1. Đọc dữ liệu
metadata = pd.read_csv('/content/domain_worker_desires.csv')
desires = pd.read_csv('/content/domain_worker_metadata.csv')
task_statements = pd.read_csv('/content/task_statement_with_metadata.csv')
experts = pd.read_csv('/content/expert_rated_technological_capability.csv')
print("Cột trong desires:", desires.columns.tolist())
print("Cột trong metadata:", metadata.columns.tolist())

#2. Gộp file
# Gộp theo User ID
df_merged = pd.merge(metadata, desires, on='User ID', how='inner')
# Gộp tiếp theo Task ID để lấy đánh giá của chuyên gia
final_merged_df = pd.merge(df_merged, task_statements, on='Task ID', how='left')
# Xem trước dữ liệu tổng hợp
final_merged_df.head()

# Đổi tên cột _x thành tên chuẩn, sạch sẽ để đưa vào bài viết nghiên cứu
if 'Occupation (O*NET-SOC Title)_x' in final_merged_df.columns:
    final_merged_df = final_merged_df.rename(columns={'Occupation (O*NET-SOC Title)_x': 'Occupation'})

#Đổi tên cột Task_x thành tên chuẩn
if 'Task_x' in final_merged_df.columns:
  final_merged_df = final_merged_df.rename(columns={'Task_x': 'Task'})

# Xóa cột _y (nếu có) phát sinh từ tệp gộp thứ hai để tránh trùng lặp dữ liệu
if 'Occupation (O*NET-SOC Title)_y' in final_merged_df.columns:
    final_merged_df = final_merged_df.drop(columns=['Occupation (O*NET-SOC Title)_y'])

# Kiểm tra & Xứ lý giá trị thiếu
print(final_merged_df.isnull().sum())
#Xử lý giá trị thiếu
# Sử dụng trung vị (Median) tốt hơn trung bình (Mean) vì biến lương thường bị lệch (skewed).

wage_median = final_merged_df['Occupation Mean Annual Wage'].median()
emp_median = final_merged_df['Occupation Employment'].median()

final_merged_df['Occupation Mean Annual Wage'] = final_merged_df['Occupation Mean Annual Wage'].fillna(wage_median)
final_merged_df['Occupation Employment'] = final_merged_df['Occupation Employment'].fillna(emp_median)

print(f"\n-> Đã điền 1512 vị trí trống bằng Mức lương trung vị ngành: {wage_median:,.0f} USD")

print("\n--- Sau khi xử lý ---")
print(f"Số lượng cột bị thiếu 'Occupation': {final_merged_df['Occupation'].isnull().sum()}")
print(f"Số lượng cột bị thiếu 'Wage': {final_merged_df['Occupation Mean Annual Wage'].isnull().sum()}")
print(f"Tổng số dòng hiện tại của bộ dữ liệu nghiên cứu: {final_merged_df.shape[0]}")

"""### **XỬ LÝ NGOẠI LAI (OUTLIERS)**

**1. Biến Thu nhập (Income)**

Do biến Thu nhập (Income) ban đầu được thu thập dưới dạng biến khoảng, nghiên cứu đã tiến hành kỹ thuật chuyển đổi sang biến liên tục bằng giá trị trung vị của khoảng (Midpoint transformation). Nhằm triệt tiêu ảnh hưởng của các giá trị ngoại lai cực đoan có thể làm chệch hệ số góc của đường hồi quy, nghiên cứu áp dụng phương pháp Winsorization tại phân vị 1% và 99%. Kết quả giúp đưa độ lệch (Skewness) của biến thu nhập về mức an toàn, đảm bảo giả định phân phối chuẩn trong mô hình OLS.

**2. Biến LLM Familiarity:**

Biến Mức độ quen thuộc với AI (LLM Familiarity) được chuẩn hóa sang thang đo thứ bậc từ 1 đến 5. Để ngăn chặn hiện tượng phân tách hoàn toàn (Complete Separation) hoặc tăng sai số chuẩn do các nhóm thiểu số gây ra, các biểu mẫu quan sát thuộc các nhóm có tần suất xuất hiện cực thấp (< 5%) đã được gộp một cách hợp lý vào nhóm liền kề nhằm đảm bảo tính vững của các ước lượng hồi quy.
"""

# Xử lý giá trị ngoại lai
print("XỬ LÝ NGOẠI LAI (OUTLIERS)")
# =========================================================================
# XỬ LÝ BIẾN INCOME
# =========================================================================

# Bước 1.1: Chuyển đổi từ dạng khoảng (Text) sang dạng số liên tục (Midpoint)
def convert_income_to_numeric(val):
    if pd.isna(val):
        return np.nan
    val = str(val).strip()

    # Ánh xạ theo các khoảng xuất hiện trong file metadata của bạn
    if '30-60K' in val: return 45000
    elif '60-86K' in val: return 73000
    elif '86K-165K' in val: return 125500
    elif 'under 30K' in val or '<30K' in val: return 15000
    elif 'above 165K' in val or '>165K' in val: return 210000 # Ước lượng biên trên
    return np.nan

final_merged_df['Income_Numeric'] = final_merged_df['Income'].apply(convert_income_to_numeric)

# Bước 1.2: Áp dụng phương pháp xử lý ngoại lai nghiêm ngặt cho Income
# Cách A: Winsorize - Cắt ngọn và đưa về phân vị 1% và 99% (Tối ưu nhất cho hồi quy)
final_merged_df['Income_Cleaned'] = mstats.winsorize(final_merged_df['Income_Numeric'], limits=[0.01, 0.01])

# =========================================================================
# CHÂN TRANG 2: XỬ LÝ BIẾN LLM FAMILIARITY (Mức độ quen thuộc)
# =========================================================================

# Bước 2.1: Chuyển đổi biến phân loại thứ bậc sang Thang đo số (1 -> 4)
# Kiểm tra chuỗi ký tự thực tế trong file metadata của bạn để ánh xạ chính xác
familiarity_map = {
    'I have never heard of them': 1,
    'I know what they are, but have never used them': 2,
    'I have some experience using them.': 3,
    'I use them regularly.': 4,
    'I use them every day in my work.': 5
}
final_merged_df['LLM_Familiarity_Numeric'] = final_merged_df['LLM Familiarity'].map(familiarity_map)

# Bước 2.2: Xử lý "ngoại lai" dạng tần suất thấp (Rare Categories) cho biến thứ bậc
# Tính toán tỷ lệ phần trăm của từng nhóm phản hồi
frequencies = final_merged_df['LLM_Familiarity_Numeric'].value_counts(normalize=True)
print("\nPhân phối tỷ lệ của biến LLM Familiarity:\n", frequencies)

# NẾU CÓ NHÓM CÓ TỶ LỆ < 5% (Ví dụ nhóm 1 hoặc nhóm 5 quá ít người chọn):
# Tiến hành gộp nhóm đó vào nhóm liền kề để tránh làm nhiễu sai số chuẩn (Standard Error) trong hồi quy
# Ví dụ dưới đây: Nếu nhóm 1 (chưa từng nghe qua) quá ít, gộp chung với nhóm 2 thành nhóm "Ít/Chưa quen thuộc"
final_merged_df['LLM_Familiarity_Cleaned'] = final_merged_df['LLM_Familiarity_Numeric'].replace({1: 2})


# =========================================================================
# BƯỚC KHỬ TRÙNG CUỐI CÙNG: KIỂM TRA ĐỘ LỆCH (SKEWNESS)
# =========================================================================
print("\n--- KIỂM TRA ĐỘ SẠCH CỦA HỆ SỐ ---")
print(f"Độ lệch (Skewness) của Income trước xử lý: {final_merged_df['Income_Numeric'].skew():.2f}")
print(f"Độ lệch (Skewness) của Income sau khi xử lý Outlier: {final_merged_df['Income_Cleaned'].skew():.2f}")
print(f"Cỡ mẫu nghiên cứu còn lại sau khi lọc loại Outliers: {final_merged_df.shape[0]} dòng")

# Chuyển đổi thành biến giả: 0 = Kinh nghiệm cơ bản (3.0), 1 = Sử dụng thường xuyên (4.0)
final_merged_df['LLM_Familiarity_Dummy'] = final_merged_df['LLM_Familiarity_Numeric'].map({3.0: 0, 4.0: 1})

print(final_merged_df['LLM_Familiarity_Dummy'].value_counts(normalize=True))
# Đầu ra sẽ là: 1.0 (thường xuyên) chiếm ~60.6% và 0.0 (cơ bản) chiếm ~39.4%

# Lọc dữ liệu cho ngành Khoa học máy tính và chọn các cột liên quan
cs_keywords = ['Software', 'Computer', 'Data', 'Programmer', 'Developer']
cs_final_df = final_merged_df[final_merged_df['Occupation'].str.contains('|'.join(cs_keywords), na=False)]

# Chọn các cột có liên quan trực tiếp đến phân tích trong ngành Khoa học máy tính
relevant_cols = [
    'Task ID',
    'Occupation',
    'Task',
    'User ID',
    'Age',
    'Self-reported Expertise',
    'Automation Desire Rating',
    'Core Skill Rating',
    'Job Security Rating',
    'Enjoyment Rating',
    'Income_Cleaned',
    'LLM_Familiarity_Cleaned',
    'LLM_Familiarity_Dummy',
    'Occupation Mean Annual Wage',
    'Occupation Employment',
    'Skill (O*NET Work Activity)',
    'Physical Action Requirement',
    'Interpersonal Communication Requirement',
    'Involved Uncertainty',
    'Domain Expertise Requirement',
    'Human Agency Scale Rating'
]

cs_final_df = cs_final_df[relevant_cols]

print(cs_final_df.head())
print(f"\nSố dòng trong bảng mới cho ngành Khoa học máy tính: {cs_final_df.shape[0]}")
print(f"Các cột trong bảng mới: {cs_final_df.columns.tolist()}")

"""# **2. Feature Engineering**

## **2.1 Biến Generation (Thế hệ): Chuyển đổi cột Age thành biến phân loại.**
- Dưới 28 tuổi: Gen Z (Đại diện cho nhóm lao động trẻ, xu hướng tìm kiếm cân bằng).

- 28 - 43 tuổi: Millennials (Nhóm chuyển giao).

- Trên 43 tuổi: Gen X+ (Nhóm mang đậm văn hóa lao động truyền thống "cần cù bù thông minh").

Biến này đại diện cho sự khác biệt về bối cảnh xã hội và văn hóa lao động giữa các thế hệ.
"""

def classify_generation(age):
    if age < 28:
        return 'Gen Z'
    elif 28 <= age <= 43:
        return 'Millennials'
    else:
        return 'Gen X+'

cs_final_df['Generation'] = cs_final_df['Age'].apply(classify_generation)

print("Phân phối thế hệ trong dữ liệu:")
print(cs_final_df['Generation'].value_counts())
print("\nPhần trăm từng thế hệ:")
print(cs_final_df['Generation'].value_counts(normalize=True).round(2))

#Xuất file CSV đã xử lý
cs_final_df.to_csv('cs_final_df_processed.csv', index=False)

"""# **3. Phân tích hiện trạng ngành Khoa học máy tính**

Câu hỏi phân tích:
1. Ngành CS hiện tại ai đang dùng AI nhiều nhất?

2. Họ dùng AI để làm những việc gì? Có thật sự chỉ để code không?

3. Tâm lý của họ đang hoang mang hay hào hứng đón nhận?

4. Bản chất công việc của họ hiện tại đang bận rộn và quan trọng ra sao?

###  **3.1 User Segmentation & Adoption: Ai là người đang dùng AI nhiều nhất?**
Thống kê tần suất sử dụng LLM (Coding, Analysis, Data Processing) theo Generation, mức lương, kinh nghiệm
"""

# 1. Lọc dữ liệu cho các ngành nghề Khoa học máy tính và chọn các cột liên quan
cs_keywords = ['Software', 'Computer', 'Data', 'Programmer', 'Developer']
cs_llm_data = final_merged_df[final_merged_df['Occupation'].str.contains('|'.join(cs_keywords), na=False)].copy()

# 2. Chọn các cột về mức lương đã làm sạch, kinh nghiệm và các loại sử dụng LLM cụ thể
llm_usage_cols = [
    'LLM Usage by Type - Coding',
    'LLM Usage by Type - Analysis',
    'LLM Usage by Type - Data Processing'
]
analysis_cols = ['User ID', 'Occupation', 'Income_Cleaned', 'Experience', 'Generation'] + llm_usage_cols

cs_llm_data = cs_llm_data[analysis_cols]

# Debug: Inspect raw values of LLM Usage columns before conversion
print("\n--- Debugging LLM Usage Columns (Raw values in cs_llm_data before map) ---")
for col in llm_usage_cols:
    print(f"Column: {col}")
    print(cs_llm_data[col].value_counts(dropna=False).to_string())
    print("----")

# 3. Chuyển đổi các cột sử dụng LLM từ tần suất ('Daily', 'Weekly', etc.) thành 1/0 (có sử dụng/không sử dụng)
llm_frequency_to_binary_map = {
    'Daily': 1,
    'Weekly': 1,
    'Monthly': 1,
    'Never': 0
}
for col in llm_usage_cols:
    # Using map to convert frequency terms to binary (1 for usage, 0 for never), and any other values (like NaNs) to NaN
    cs_llm_data[col] = cs_llm_data[col].map(llm_frequency_to_binary_map).fillna(0).astype(int)

# Debug: Inspect values of LLM Usage columns after conversion
print("\n--- Debugging LLM Usage Columns (Values in cs_llm_data after map/fillna/astype) ---")
for col in llm_usage_cols:
    print(f"Column: {col} sum: {cs_llm_data[col].sum()}")
    print(f"Column: {col} mean (percentage 'Yes'): {cs_llm_data[col].mean() * 100:.2f}%")
    print("----")


# 4. Thống kê tần suất sử dụng LLM theo mức lương
# Tạo các khoảng (bins) mức lương dựa trên phân vị
income_bins = pd.qcut(cs_llm_data['Income_Cleaned'], q=4, duplicates='drop', precision=0) # Added precision=0 for cleaner bin labels

print("\n--- Tần suất sử dụng LLM (Coding, Analysis, Data Processing) theo Mức lương (Tỷ lệ % người dùng) ---")
llm_usage_by_income = cs_llm_data.groupby(income_bins, observed=True)[llm_usage_cols].mean() * 100
print(llm_usage_by_income)

# Debug: Inspect raw unique values of Experience column before grouping
print("\n--- Debugging Experience Column (Raw unique values in cs_llm_data) ---")
print(cs_llm_data['Experience'].unique())
print("----")

# 5. Thống kê tần suất sử dụng LLM theo kinh nghiệm
print("\n--- Tần suất sử dụng LLM (Coding, Analysis, Data Processing) theo Kinh nghiệm (Tỷ lệ % người dùng) ---")
llm_usage_by_experience_raw = cs_llm_data.groupby('Experience', observed=True)[llm_usage_cols].mean() * 100

# Debug: Print the index of the raw grouped DataFrame
print("Index of llm_usage_by_experience_raw:", llm_usage_by_experience_raw.index.tolist())
print(llm_usage_by_experience_raw)

# Sắp xếp theo thứ tự kinh nghiệm để dễ đọc hơn, using actual observed categories
experience_order = ['Less than 1 year', '1-2 year', '3-5 years', '6-10 years', 'More than 10 years']
existing_experience_order = [exp for exp in experience_order if exp in llm_usage_by_experience_raw.index]

# If there are still mismatches, use the available index directly
if not existing_experience_order and not llm_usage_by_experience_raw.empty:
    print("\nWarning: Standard experience order not fully matched. Using actual experience categories from data for sorting.")
    llm_usage_by_experience = llm_usage_by_experience_raw.reindex(llm_usage_by_experience_raw.index)
else:
    llm_usage_by_experience = llm_usage_by_experience_raw.reindex(existing_experience_order)
print(llm_usage_by_experience)

# 6. Thống kê tần suất sử dụng LLM theo Generation
print("\n--- Tần suất sử dụng LLM (Coding, Analysis, Data Processing) theo Generation (Tỷ lệ % người dùng) ---")
llm_usage_by_generation = cs_llm_data.groupby('Generation', observed=True)[llm_usage_cols].mean() * 100
print(llm_usage_by_generation)

"""### **3.2 Hành vi sử dụng AI theo Chuyên môn (Behavioral Breakdown)**

"""

# 1. Filter data for Computer Science occupations
cs_keywords = ['Software', 'Computer', 'Data', 'Programmer', 'Developer']
cs_llm_usage_df = final_merged_df[final_merged_df['Occupation'].str.contains('|'.join(cs_keywords), na=False)].copy()

# 2. Define LLM Usage Type columns and ordinal mapping
llm_usage_cols_for_radar = [
    'LLM Usage by Type - Information Access',
    'LLM Usage by Type - Edit',
    'LLM Usage by Type - Idea Generation',
    'LLM Usage by Type - Communication',
    'LLM Usage by Type - Analysis',
    'LLM Usage by Type - Decision',
    'LLM Usage by Type - Coding',
    'LLM Usage by Type - System Design',
    'LLM Usage by Type - Data Processing'
]

# Ordinal mapping based on user's request
llm_usage_ordinal_map = {
    'Never': 1,
    'Rarely': 2, # Assuming 'Rarely' might exist or for completeness based on common scales
    'Monthly': 3,
    'Weekly': 4,
    'Daily': 5
}

# 3. Apply ordinal encoding and handle NaNs
for col in llm_usage_cols_for_radar:
    # Fillna with 0 for cases where there's no response, implying no usage or not applicable,
    # then map existing text values to ordinal scores.
    # For any values not in the map (e.g., actual NaNs not handled by previous fills, or unexpected text), they will become NaN here.
    # Then fill those final NaNs with 0, effectively meaning no usage if they weren't explicitly 'Never'.
    cs_llm_usage_df[col + '_Score'] = cs_llm_usage_df[col].map(llm_usage_ordinal_map).fillna(0)

# Extract the score columns for aggregation
score_cols = [col + '_Score' for col in llm_usage_cols_for_radar]

# 4. Calculate mean scores for each usage type
mean_usage_scores = cs_llm_usage_df[score_cols].mean()

# Rename columns for better plotting labels
plot_labels = [
    'Information Access',
    'Edit',
    'Idea Generation',
    'Communication',
    'Analysis',
    'Decision',
    'Coding',
    'System Design',
    'Data Processing'
]
mean_usage_scores.index = plot_labels

# 5. Prepare data for Radar Chart
values = mean_usage_scores.values
N = len(plot_labels)

# What will be the angle of each axis in the plot? (divide the plot / number of variable)
angles = [n / float(N) * 2 * np.pi for n in range(N)]
angles += angles[:1] # Repeat the first value to close the circle

# Repeat the first value to close the circle
values = np.append(values, values[:1])

# 6. Create the Radar Chart
fig, ax = plt.subplots(figsize=(10, 10), subplot_kw=dict(polar=True))

# Plot data
ax.plot(angles, values, color='mediumseagreen', linewidth=2, linestyle='solid') # Changed color to 'mediumseagreen'
ax.fill(angles, values, color='lightgreen', alpha=0.4) # Changed fill color to 'lightgreen'

# Add labels to axes
ax.set_theta_offset(np.pi / 2)
ax.set_theta_direction(-1)
plt.xticks(angles[:-1], plot_labels, color='grey', size=12)

# Draw ylabels
ax.set_rlabel_position(0)
plt.yticks([1, 2, 3, 4, 5], ["Never (1)", "Rarely (2)", "Monthly (3)", "Weekly (4)", "Daily (5)"], color="grey", size=10)
plt.ylim(0, 5)

plt.title('Average LLM Usage Behavior by Type in Computer Science Occupations', size=16, color='black', y=1.1)
plt.show()

"""**Nhận xét:**

**AI được sử dụng cho những công việc gì? Có thật sự chỉ để code không?**

Dựa trên biểu đồ Radar Chart về hành vi sử dụng LLM trung bình của các chuyên gia trong ngành Khoa học Máy tính, chúng ta có thể thấy:

AI không chỉ được sử dụng riêng cho các tác vụ viết code mà còn cho nhiều hoạt động khác nhau với mức độ đáng kể:

*   **Coding (Lập trình):** AI được sử dụng khá phổ biến để hỗ trợ trong việc viết code.
*   **Information Access (Truy cập thông tin):** Đây là một trong những ứng dụng AI được sử dụng nhiều nhất, cho thấy các chuyên gia dùng AI để tìm kiếm và tổng hợp thông tin nhanh chóng.
*   **Edit (Chỉnh sửa):** AI cũng được dùng thường xuyên trong việc chỉnh sửa nội dung hoặc code.
*   **Idea Generation (Tạo ý tưởng):** Các chuyên gia tận dụng AI để khám phá và phát triển các ý tưởng mới.
*   **Analysis (Phân tích):** AI hỗ trợ mạnh mẽ trong việc phân tích dữ liệu và các vấn đề phức tạp.
*   **Communication (Giao tiếp):** Một phần mềm AI cũng được dùng để hỗ trợ giao tiếp.
*   **Decision (Ra quyết định):** Mặc dù không cao bằng các tác vụ khác, AI vẫn được sử dụng để hỗ trợ quá trình ra quyết định.
*   **System Design (Thiết kế hệ thống):** AI cũng đóng vai trò nhất định trong việc hỗ trợ thiết kế các hệ thống phức tạp.
*   **Data Processing (Xử lý dữ liệu):** AI được sử dụng để xử lý và quản lý dữ liệu.

**Kết luận:**

AI trong ngành Khoa học Máy tính được ứng dụng rất đa dạng, không chỉ giới hạn ở việc viết code. Các chuyên gia sử dụng AI để nâng cao hiệu quả trong hầu hết các khía cạnh của công việc, từ nghiên cứu và phát triển ý tưởng đến phân tích và xử lý dữ liệu. Điều này phản ánh tiềm năng to lớn của AI trong việc thay đổi cách thức làm việc trong ngành.

# **3.3 Tâm lý và Thái độ đối với AI (Psychology & Attitudes)**
"""

# 1. Filter data for Computer Science occupations
cs_keywords = ['Software', 'Computer', 'Data', 'Programmer', 'Developer']
cs_df_attitudes = final_merged_df[final_merged_df['Occupation'].str.contains('|'.join(cs_keywords), na=False)].copy()

# Robustly clean 'LLM Use in Work' column for comparison
# Convert to string, strip spaces, and convert to title case for consistent matching
cs_df_attitudes['LLM Use in Work Cleaned'] = cs_df_attitudes['LLM Use in Work'].astype(str).str.strip().str.capitalize()

# Check the distribution of 'LLM Use in Work Cleaned' for CS occupations
print("Distribution of 'LLM Use in Work' in Computer Science occupations:")
print(cs_df_attitudes['LLM Use in Work Cleaned'].value_counts())

# 2. Define AI usage groups: 'Daily User' and 'Never User'
# Now using the actual values observed in the value_counts() output
cs_df_attitudes['AI_Usage_Group'] = cs_df_attitudes['LLM Use in Work Cleaned'].apply(
    lambda x:
    'Daily User' if x == 'Yes, i use them every day in my work.' else (
        'Never User' if x in ['No, i have not used them for any work-related activities.', 'No, i\'ve never heard of them.'] else np.nan
    )
)

# Drop rows where AI_Usage_Group is NaN (i.e., not 'Daily User' or 'Never User')
cs_df_attitudes.dropna(subset=['AI_Usage_Group'], inplace=True)

# Check if the DataFrame is empty after filtering
if cs_df_attitudes.empty:
    print("\nWarning: No 'Daily User' or 'Never User' found in the 'LLM Use in Work' column for Computer Science occupations after cleaning. Cannot proceed with plotting or correlation.")
else:
    print(f"Shape after dropping non-Daily/Never users: {cs_df_attitudes.shape}")
    print("--- AI Attitude Analysis for Computer Science Occupations ---")

    # Debugging Raw Attitude Columns after AI_Usage_Group filter
    print("\n--- Debugging Raw Attitude Columns after AI_Usage_Group filter ---")
    print(f"Value counts for 'AI Tedious Work Attitude':\n{cs_df_attitudes['AI Tedious Work Attitude'].value_counts(dropna=False)}")
    print(f"Value counts for 'AI Suffering Attitude':\n{cs_df_attitudes['AI Suffering Attitude'].value_counts(dropna=False)}")
    print("-------------------------------------------------------------------")

    # Define a mapping for attitude values to standardize them
    attitude_value_map = {
        'Strongly disagree': 'Strongly Disagree',
        'Somewhat disagree': 'Disagree',
        'Neither agree nor disagree': 'Neutral',
        'Somewhat agree': 'Agree',
        'Strongly agree': 'Strongly Agree'
    }

    attitude_cols = ['AI Tedious Work Attitude', 'AI Suffering Attitude']
    attitude_order = ['Strongly Disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly Agree']

    for attitude_col in attitude_cols:
        # Standardize attitude values first
        cs_df_attitudes[attitude_col + '_Cleaned'] = cs_df_attitudes[attitude_col].map(attitude_value_map)

        # Debug cleaned attitude values
        print(f"\nValue counts for cleaned '{attitude_col}':\n{cs_df_attitudes[attitude_col + '_Cleaned'].value_counts(dropna=False)}")

        # Check if there is any non-null data for the current attitude_col for the selected groups
        if cs_df_attitudes[attitude_col + '_Cleaned'].dropna().empty:
            print(f"Warning: No valid non-null data for '{attitude_col}' in the filtered Computer Science occupations. Skipping plot for this attitude.")
            continue

        # Calculate the proportion of each attitude response within each AI_Usage_Group
        attitude_proportions = cs_df_attitudes.groupby('AI_Usage_Group')[attitude_col + '_Cleaned'].value_counts(normalize=True).mul(100).unstack(fill_value=0)

        # Print debug info for attitude_proportions (optional, can be removed in final version)
        # print(f"\nattitude_proportions for {attitude_col}:\n{attitude_proportions}")

        # Ensure all attitude categories are present, fill missing with 0 for plotting
        for cat in attitude_order:
            if cat not in attitude_proportions.columns:
                attitude_proportions[cat] = 0
        attitude_proportions = attitude_proportions[attitude_order]

        # If attitude_proportions is still empty or all zeros after processing, skip plotting this chart
        if attitude_proportions.empty or attitude_proportions.sum().sum() == 0:
            print(f"Warning: 'attitude_proportions' for '{attitude_col}' is empty or all zeros. Skipping chart generation.")
            continue

        # Determine colormap based on the attitude type for better visual intuition
        if 'Tedious Work' in attitude_col:
            cmap_attitude = 'Greens' # More green suggests more positive agreement about AI helping with tedious work
            title_prefix = "AI as a 'Savior' (Helps with Tedious Work)"
        elif 'Suffering' in attitude_col:
            cmap_attitude = 'Reds'   # More red suggests more negative agreement about AI causing suffering
            title_prefix = "AI as a 'Threat' (Causes Suffering)"
        else:
            cmap_attitude = 'viridis' # Fallback for other attitudes

        # Plotting the 100% Stacked Bar Chart
        fig, ax = plt.subplots(figsize=(10, 6))
        attitude_proportions.plot(kind='bar', stacked=True, cmap=cmap_attitude, ax=ax)

        plt.title(f'{title_prefix}: {attitude_col.replace("AI ", "").replace(" Attitude", "")} by LLM Usage Frequency', fontsize=14)
        plt.xlabel('LLM Usage Group', fontsize=12)
        plt.ylabel('Percentage (%)', fontsize=12)
        plt.xticks(rotation=0)
        plt.legend(title='Agreement Level', bbox_to_anchor=(1.05, 1), loc='upper left')
        plt.tight_layout()
        plt.show()

    # --- Correlation Analysis: LLM Usage vs. AI Suffering ---
    print("\n--- Correlation Analysis: LLM Usage vs. AI Suffering ---")

    # Map LLM Use in Work to numerical for correlation (ordinal scale)
    # Update mapping to include all relevant categories and their ordinal values
    llm_use_numeric_map = {
        'No, i\'ve never heard of them.': 1, # Lowest familiarity/usage
        'No, i have not used them for any work-related activities.': 1, # Treated as 'Never'
        'Yes, i have used them occasionally for specific tasks.': 2, # Occasional use (These values are filtered out by AI_Usage_Group)
        'Yes, i use them every week in my work.': 3, # Weekly use (These values are filtered out by AI_Usage_Group)
        'Yes, i use them every day in my work.': 4  # Daily use
    }
    cs_df_attitudes['LLM_Use_Numeric'] = cs_df_attitudes['LLM Use in Work Cleaned'].map(llm_use_numeric_map)

    # Map AI Suffering Attitude to numerical (1=Strongly Disagree, 5=Strongly Agree)
    suffering_numeric_map = {
        'Strongly Disagree': 1,
        'Disagree': 2,
        'Neutral': 3,
        'Agree': 4,
        'Strongly Agree': 5
    }
    # Use the cleaned column for mapping to numeric values
    cs_df_attitudes['AI_Suffering_Numeric'] = cs_df_attitudes['AI Suffering Attitude_Cleaned'].map(suffering_numeric_map)

    # Calculate Pearson Correlation Coefficient
    # Drop rows with NaN in these specific columns for accurate correlation calculation
    valid_correlation_df = cs_df_attitudes.dropna(subset=['LLM_Use_Numeric', 'AI_Suffering_Numeric'])

    if not valid_correlation_df.empty:
        correlation = valid_correlation_df['LLM_Use_Numeric'].corr(valid_correlation_df['AI_Suffering_Numeric'])
        print(f"Pearson Correlation between LLM Usage Frequency and AI Suffering Attitude: {correlation:.2f}")

        # Compare average suffering score between Daily Users and Never Users
        # Ensure 'Daily User' and 'Never User' groups exist in valid_correlation_df before calculating mean
        daily_users_suffering_mean = valid_correlation_df[valid_correlation_df['AI_Usage_Group'] == 'Daily User']['AI_Suffering_Numeric'].mean()
        never_users_suffering_mean = valid_correlation_df[valid_correlation_df['AI_Usage_Group'] == 'Never User']['AI_Suffering_Numeric'].mean()

        print(f"Average AI Suffering Score for Daily Users: {daily_users_suffering_mean:.2f}")
        print(f"Average AI Suffering Score for Never Users: {never_users_suffering_mean:.2f}")

        if daily_users_suffering_mean < never_users_suffering_mean:
            print("Observation: Daily users show a lower average AI Suffering score compared to never users (suggesting less perceived threat).")
        elif daily_users_suffering_mean > never_users_suffering_mean:
            print("Observation: Daily users show a higher average AI Suffering score compared to never users (suggesting more perceived threat).")
        else:
            print("Observation: Daily users and never users show a similar average AI Suffering score.")
    else:
        print("Warning: Not enough valid data in 'LLM_Use_Numeric' and/or 'AI_Suffering_Numeric' after filtering to calculate correlation or compare average suffering scores. This may be due to missing attitude data for the selected usage groups.")

"""### **3.3.1 Phân tích Tương quan: Mức độ sử dụng LLM và Thái độ theo Thế hệ**"""

# Tái tạo dataframe cơ sở cho các ngành nghề Khoa học Máy tính từ final_merged_df
# Điều này đảm bảo chúng ta có tất cả các cột gốc và áp dụng các chuyển đổi một cách nhất quán
cs_correlation_analysis_df = final_merged_df[final_merged_df['Occupation'].str.contains('|'.join(cs_keywords), na=False)].copy()

# Thêm cột 'Generation' nếu chưa có
def classify_generation(age):
    if age < 28:
        return 'Gen Z'
    elif 28 <= age <= 43:
        return 'Millennials'
    else:
        return 'Gen X+'
cs_correlation_analysis_df['Generation'] = cs_correlation_analysis_df['Age'].apply(classify_generation)

# Chuẩn hóa cột 'LLM Use in Work' để đảm bảo khớp chính xác khi ánh xạ
cs_correlation_analysis_df['LLM Use in Work Cleaned'] = cs_correlation_analysis_df['LLM Use in Work'].astype(str).str.strip().str.capitalize()

# Ánh xạ 'LLM Use in Work Cleaned' sang thang đo số cho mục đích tương quan
llm_use_numeric_map = {
    'No, i\'ve never heard of them.': 1,
    'No, i have not used them for any work-related activities.': 1,
    'Yes, i have used them occasionally for specific tasks.': 2,
    'Yes, i use them every week in my work.': 3,
    'Yes, i use them every day in my work.': 4
}
cs_correlation_analysis_df['LLM_Use_Numeric'] = cs_correlation_analysis_df['LLM Use in Work Cleaned'].map(llm_use_numeric_map)

# Ánh xạ các cột thái độ sang thang đo số (1=Hoàn toàn không đồng ý, 5=Hoàn toàn đồng ý)
general_attitude_numeric_map = {
    'Strongly disagree': 1,
    'Somewhat disagree': 2,
    'Neither agree nor disagree': 3,
    'Somewhat agree': 4,
    'Strongly agree': 5
}

attitude_cols_for_corr = [
    'AI Tedious Work Attitude',
    'AI Job Importance Attitude',
    'AI Daily Interest Attitude',
    'AI Suffering Attitude'
]

numerical_attitude_cols = []
for col in attitude_cols_for_corr:
    new_col_name = col.replace(' Attitude', '') + '_Numeric'
    cs_correlation_analysis_df[new_col_name] = cs_correlation_analysis_df[col].map(general_attitude_numeric_map)
    numerical_attitude_cols.append(new_col_name)

# Lọc bỏ các dòng có giá trị NaN ở các cột quan trọng cho phân tích tương quan
cs_correlation_analysis_df.dropna(subset=['Generation', 'LLM_Use_Numeric'] + numerical_attitude_cols, inplace=True)

# Tính toán hệ số tương quan theo từng Thế hệ
correlation_results = {}
for generation in cs_correlation_analysis_df['Generation'].unique():
    gen_df = cs_correlation_analysis_df[cs_correlation_analysis_df['Generation'] == generation].copy()

    if not gen_df.empty and len(gen_df) > 1: # Cần ít nhất 2 điểm dữ liệu để tính tương quan
        gen_correlations = {}
        for att_col_num in numerical_attitude_cols:
            corr_value = gen_df['LLM_Use_Numeric'].corr(gen_df[att_col_num])
            gen_correlations[att_col_num.replace('_Numeric', '')] = corr_value
        correlation_results[generation] = gen_correlations
    else:
        # Nếu không đủ dữ liệu, điền NaN
        correlation_results[generation] = {att.replace('_Numeric', ''): np.nan for att in numerical_attitude_cols}

# Trình bày kết quả dưới dạng DataFrame
correlation_df_final = pd.DataFrame.from_dict(correlation_results, orient='index')
correlation_df_final.index.name = 'Generation'

print("\n--- Tương quan giữa Tần suất sử dụng LLM và Thái độ đối với AI theo Thế hệ ---")
display(correlation_df_final.round(2))

"""### **Trực quan hóa: Mức độ lo ngại về 'AI gây đau khổ' theo Thế hệ**"""

import matplotlib.pyplot as plt
import seaborn as sns

# Calculate the average AI Suffering Score for each Generation
average_suffering_by_generation = cs_correlation_analysis_df.groupby('Generation')['AI Suffering_Numeric'].mean().reset_index()

# Define a custom order for generations for better visualization
generation_order = ['Gen Z', 'Millennials', 'Gen X+']
average_suffering_by_generation['Generation'] = pd.Categorical(
    average_suffering_by_generation['Generation'],
    categories=generation_order,
    ordered=True
)
average_suffering_by_generation = average_suffering_by_generation.sort_values('Generation')

plt.figure(figsize=(10, 6))
sns.barplot(
    x='Generation',
    y='AI Suffering_Numeric',
    data=average_suffering_by_generation,
    palette='Reds_d'
)
plt.title('Average AI Suffering Attitude by Generation', fontsize=16)
plt.xlabel('Generation', fontsize=12)
plt.ylabel('Average AI Suffering Score (1=Strongly Disagree, 5=Strongly Agree)', fontsize=12)
plt.ylim(1, 5) # Set y-axis limits to match the score range
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

"""### **3.4 Đặc thù các tác vụ gốc của ngành CS (Baseline Task Analysis)**"""

import ast # To convert string representation of list to actual list

# 1. Identify Computer Science occupations from the final_merged_df
cs_keywords = ['Software', 'Computer', 'Data', 'Programmer', 'Developer']
cs_occupations = final_merged_df[final_merged_df['Occupation'].str.contains('|'.join(cs_keywords), na=False)]['Occupation'].unique()

# 2. Filter the original task_statements for Core tasks within these identified CS occupations
core_cs_tasks_df = task_statements[
    task_statements['Occupation (O*NET-SOC Title)'].isin(cs_occupations) &
    (task_statements['Task Type'] == 'Core')
].copy()

# 3. Ensure numerical columns are correctly typed and handle potential NaNs
core_cs_tasks_df.dropna(subset=['Frequency', 'Importance', 'Occupation Employment'], inplace=True)
core_cs_tasks_df['Frequency'] = pd.to_numeric(core_cs_tasks_df['Frequency'])
core_cs_tasks_df['Importance'] = pd.to_numeric(core_cs_tasks_df['Importance'])
core_cs_tasks_df['Occupation Employment'] = pd.to_numeric(core_cs_tasks_df['Occupation Employment'])

# Convert 'Skill (O*NET Work Activity)' from string representation of list to actual list
def parse_skill_list(skill_str):
    try:
        return ast.literal_eval(skill_str)
    except (ValueError, SyntaxError):
        return [] # Return empty list if parsing fails

core_cs_tasks_df['Skill_List'] = core_cs_tasks_df['Skill (O*NET Work Activity)'].apply(parse_skill_list)

# 4. Create the Scatter Plot
plt.figure(figsize=(14, 8))
sns.scatterplot(
    data=core_cs_tasks_df,
    x='Frequency',
    y='Importance',
    size='Occupation Employment', # Map to bubble size
    hue='Occupation (O*NET-SOC Title)', # Color by occupation
    sizes=(50, 2000), # Adjust min and max size of bubbles for better visualization
    alpha=0.6,
    edgecolor='w',
    linewidth=0.5
)

plt.title('Baseline Task Analysis for Core Computer Science Occupations: Frequency vs. Importance', fontsize=16)
plt.xlabel('Task Frequency (Higher = More Frequent)', fontsize=12)
plt.ylabel('Task Importance (Higher = More Important)', fontsize=12)
plt.grid(True, linestyle='--', alpha=0.7)
plt.legend(title='Occupation', bbox_to_anchor=(1.05, 1), loc='upper left', borderaxespad=0, ncol=1)
plt.tight_layout()
plt.show()

# 5. Identify pain-point tasks based on combined metrics and 'routine' skills
print("\n--- Identifying Pain-Point Tasks (High Freq, High Imp, High Emp, Routine Skill) ---")

# Define 'routine' skills keywords. These are common O*NET work activities that can be repetitive or process-oriented.
routine_skill_keywords = [
    'Processing Information',
    'Documenting/Recording Information',
    'Working with Computers', # Can be routine for some tasks
    'Updating and Using Relevant Knowledge' # Can involve routine updates
]

def has_routine_skill(skill_list, keywords):
    return any(any(keyword in s for s in skill_list) for keyword in keywords)

core_cs_tasks_df['Has_Routine_Skill'] = core_cs_tasks_df['Skill_List'].apply(lambda x: has_routine_skill(x, routine_skill_keywords))

# Calculate medians for filtering 'high' values
freq_median = core_cs_tasks_df['Frequency'].median()
imp_median = core_cs_tasks_df['Importance'].median()
emp_median_tasks = core_cs_tasks_df['Occupation Employment'].median()

# Filter for top tasks (high frequency, importance, employment) that also have routine skills
top_pain_point_tasks = core_cs_tasks_df[
    (core_cs_tasks_df['Frequency'] >= freq_median) &
    (core_cs_tasks_df['Importance'] >= imp_median) &
    (core_cs_tasks_df['Occupation Employment'] >= emp_median_tasks) &
    (core_cs_tasks_df['Has_Routine_Skill'] == True)
].sort_values(by=['Frequency', 'Importance', 'Occupation Employment'], ascending=[False, False, False])

print("\nTop Core CS Tasks (High Frequency, High Importance, High Employment, with Routine Skills):")
if not top_pain_point_tasks.empty:
    print(top_pain_point_tasks[['Task', 'Occupation (O*NET-SOC Title)', 'Frequency', 'Importance', 'Occupation Employment', 'Skill_List']].head(10).to_string())
else:
    print("No tasks found matching the criteria for high frequency, importance, employment, and routine skills.")

# Optionally, calculate a composite 'Pain_Point_Score' for more granular ranking
# Normalize employment for fair weighting
core_cs_tasks_df['Normalized_Employment'] = core_cs_tasks_df['Occupation Employment'] / core_cs_tasks_df['Occupation Employment'].max()
core_cs_tasks_df['Pain_Point_Score'] = core_cs_tasks_df['Frequency'] * core_cs_tasks_df['Importance'] * core_cs_tasks_df['Normalized_Employment']

# Increase score for tasks with routine skills
core_cs_tasks_df.loc[core_cs_tasks_df['Has_Routine_Skill'] == True, 'Pain_Point_Score'] *= 2

most_significant_pain_point_task = core_cs_tasks_df.sort_values(by='Pain_Point_Score', ascending=False).head(1)

if not most_significant_pain_point_task.empty:
    print("\n--- Most Significant Pain-Point Task (Highest Composite Score) ---")
    print(most_significant_pain_point_task[['Task', 'Occupation (O*NET-SOC Title)', 'Frequency', 'Importance', 'Occupation Employment', 'Skill_List', 'Pain_Point_Score']].to_string(index=False))
else:
    print("No task found with a significant pain-point score.")

"""### Phân tích Bản chất Công việc Ngành Khoa học máy tính (Mức độ bận rộn và Quan trọng)

Từ kết quả phân tích các tác vụ gốc (Baseline Task Analysis), chúng ta có thể thấy:

**1. Tác vụ 'Điểm đau' đáng kể nhất (Most Significant Pain-Point Task):**
- **Tác vụ:** Read technical manuals, confer with users, or conduct computer diagnostics to investigate and resolve problems or to provide technical assistance and support.
- **Ngành nghề chính:** Computer User Support Specialists
- **Tần suất thực hiện (Thang 1-7):** 6.0
- **Mức độ quan trọng (Thang 1-5):** 3.9
- **Kỹ năng liên quan:** Getting Information, Working with Computers, Communicating with Supervisors, Peers, or Subordinates

=> Đây là tác vụ thường xuyên, quan trọng và thường liên quan đến các kỹ năng mang tính quy trình trong ngành Hỗ trợ người dùng Máy tính. Nó cho thấy áp lực và tính chất lặp lại của công việc này.

**2. Các tác vụ Core có tần suất và tầm quan trọng cao, đồng thời liên quan đến kỹ năng quy trình (Top Pain-Point Tasks):**
Các tác vụ này thường yêu cầu xử lý thông tin, ghi chép, làm việc với máy tính, hoặc cập nhật kiến thức liên quan.

- **Tác vụ:** Identify, analyze, and document problems with program function, output, online screen, or content.
  - **Ngành nghề:** Software Quality Assurance Analysts and Testers
  - **Tần suất:** 6.0, **Quan trọng:** 4.7
  - **Kỹ năng:** Analyzing Data or Information, Working with Computers, Documenting/Recording Information

- **Tác vụ:** Document software defects, using a bug tracking system, and report defects to software developers.
  - **Ngành nghề:** Software Quality Assurance Analysts and Testers
  - **Tần suất:** 6.0, **Quan trọng:** 4.7
  - **Kỹ năng:** Processing Information, Communicating with Supervisors, Peers, or Subordinates

- **Tác vụ:** Install, maintain, or use software testing programs.
  - **Ngành nghề:** Software Quality Assurance Analysts and Testers
  - **Tần suất:** 6.0, **Quan trọng:** 4.3
  - **Kỹ năng:** Working with Computers

- **Tác vụ:** Read technical manuals, confer with users, or conduct computer diagnostics to investigate and resolve problems or to provide technical assistance and support.
  - **Ngành nghề:** Computer User Support Specialists
  - **Tần suất:** 6.0, **Quan trọng:** 3.9
  - **Kỹ năng:** Getting Information, Working with Computers, Communicating with Supervisors, Peers, or Subordinates

- **Tác vụ:** Document test procedures to ensure replicability and compliance with standards.
  - **Ngành nghề:** Software Quality Assurance Analysts and Testers
  - **Tần suất:** 5.0, **Quan trọng:** 4.3
  - **Kỹ năng:** Documenting/Recording Information

**Tóm tắt:**
Nhìn chung, công việc trong ngành Khoa học máy tính, đặc biệt là các vị trí hỗ trợ và kiểm thử, thường có **tần suất cao và mức độ quan trọng đáng kể**, với nhiều tác vụ liên quan đến **xử lý thông tin, ghi chép và làm việc trực tiếp với máy tính**. Những tác vụ này, dù quan trọng, vẫn tiềm ẩn tính chất lặp lại và có thể là 'điểm đau' mà AI có thể hỗ trợ.

# **Trực quan hoá**
"""

### **Phân phối "Mức độ mong muốn tự động hóa" trong ngành Khoa học máy tính**
plt.figure(figsize=(10, 6))
sns.countplot(data=cs_final_df, x='Automation Desire Rating', hue='Automation Desire Rating', palette='viridis', stat='percent', legend=False)
plt.title('Distribution of Automation Desire Rating in Computer Science Occupations')
plt.xlabel('Automation Desire Rating (1 = Low, 5 = High)')
plt.ylabel('Percentage')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

# Mức độ mong muốn tự động hóa" theo các nhóm thế hệ (Generation)
plt.figure(figsize=(12, 7))
sns.countplot(data=cs_final_df, x='Automation Desire Rating', hue='Generation', palette='viridis', stat='percent')
plt.title('Distribution of Automation Desire Rating by Generation in Computer Science Occupations')
plt.xlabel('Automation Desire Rating (1 = Low, 5 = High)')
plt.ylabel('Percentage')
plt.legend(title='Generation')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

"""### **Tần suất sử dụng AI theo từng nhóm kinh nghiệm cụ thể**"""

# Chuyển đổi DataFrame từ định dạng wide sang long để dễ dàng vẽ biểu đồ nhóm
llm_usage_melted = llm_usage_by_experience.reset_index().melt(id_vars='Experience',
                                                                 var_name='LLM Usage Type',
                                                                 value_name='Usage Percentage')

# Sắp xếp lại thứ tự kinh nghiệm để biểu đồ có ý nghĩa hơn
experience_order = ['Less than 1 year', '1-2 year', '3-5 years', '6-10 years', 'More than 10 years']
llm_usage_melted['Experience'] = pd.Categorical(llm_usage_melted['Experience'], categories=experience_order, ordered=True)
llm_usage_melted = llm_usage_melted.sort_values('Experience')

plt.figure(figsize=(14, 8))
sns.barplot(data=llm_usage_melted,
            x='Experience',
            y='Usage Percentage',
            hue='LLM Usage Type',
            palette='viridis')

plt.title('Tần suất sử dụng LLM theo nhóm Kinh nghiệm và Loại tác vụ trong ngành CS', fontsize=16)
plt.xlabel('Nhóm Kinh nghiệm', fontsize=12)
plt.ylabel('Tỷ lệ người dùng LLM (%)', fontsize=12)
plt.xticks(rotation=45, ha='right') # Xoay nhãn trục x để dễ đọc hơn
plt.legend(title='Loại tác vụ sử dụng LLM', bbox_to_anchor=(1.02, 1), loc='upper left')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

# Chuyển đổi DataFrame từ định dạng wide sang long để dễ dàng vẽ biểu đồ nhóm
llm_usage_melted_income = llm_usage_by_income.reset_index().melt(id_vars='Income_Cleaned',
                                                                   var_name='LLM Usage Type',
                                                                   value_name='Usage Percentage')

# Đổi tên cột Income_Cleaned để dễ đọc hơn trên biểu đồ
llm_usage_melted_income = llm_usage_melted_income.rename(columns={'Income_Cleaned': 'Income Group'})

# Sắp xếp lại thứ tự nhóm thu nhập (Income Groups) nếu cần, dựa trên các giá trị thực tế
# In ra các nhóm thu nhập duy nhất để kiểm tra
# print(llm_usage_melted_income['Income Group'].unique())

plt.figure(figsize=(14, 8))
sns.barplot(data=llm_usage_melted_income,
            x='Income Group',
            y='Usage Percentage',
            hue='LLM Usage Type',
            palette='RdPu') # Sử dụng palette màu hồng (Red-Purple)

plt.title('Tần suất sử dụng LLM theo nhóm Thu nhập và Loại tác vụ trong ngành CS', fontsize=16)
plt.xlabel('Nhóm Thu nhập', fontsize=12)
plt.ylabel('Tỷ lệ người dùng LLM (%)', fontsize=12)
plt.xticks(rotation=45, ha='right') # Xoay nhãn trục x để dễ đọc hơn
plt.legend(title='Loại tác vụ sử dụng LLM', bbox_to_anchor=(1.02, 1), loc='upper left')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

# Chuyển đổi DataFrame từ định dạng wide sang long để dễ dàng vẽ biểu đồ nhóm
llm_usage_melted_generation = llm_usage_by_generation.reset_index().melt(id_vars='Generation',
                                                                      var_name='LLM Usage Type',
                                                                      value_name='Usage Percentage')

# Sắp xếp lại thứ tự thế hệ (nếu cần, dựa trên thứ tự logic hoặc giá trị thực tế)
# Ví dụ: generation_order = ['Gen Z', 'Millennials', 'Gen X+']
# llm_usage_melted_generation['Generation'] = pd.Categorical(llm_usage_melted_generation['Generation'], categories=generation_order, ordered=True)
# llm_usage_melted_generation = llm_usage_melted_generation.sort_values('Generation')

plt.figure(figsize=(14, 8))
sns.barplot(data=llm_usage_melted_generation,
            x='Generation',
            y='Usage Percentage',
            hue='LLM Usage Type',
            palette='YlOrBr') # Đã đổi palette màu sang 'YlOrBr' (tông vàng)

plt.title('Tần suất sử dụng LLM theo nhóm Thế hệ và Loại tác vụ trong ngành CS', fontsize=16)
plt.xlabel('Nhóm Thế hệ', fontsize=12)
plt.ylabel('Tỷ lệ người dùng LLM (%)', fontsize=12)
plt.xticks(rotation=45, ha='right') # Xoay nhãn trục x để dễ đọc hơn
plt.legend(title='Loại tác vụ sử dụng LLM', bbox_to_anchor=(1.02, 1), loc='upper left')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

# 1. Tính toán tần suất sử dụng LLM trung bình (dưới dạng tỷ lệ %) cho từng loại tác vụ và từng ngành nghề
occupation_llm_usage = cs_llm_data.groupby('Occupation')[llm_usage_cols].mean() * 100

# 2. Đổi tên cột để dễ đọc hơn trên biểu đồ (ví dụ: loại bỏ "LLM Usage by Type -")
occupation_llm_usage.columns = [col.replace('LLM Usage by Type - ', '') for col in occupation_llm_usage.columns]

# 3. Tính toán ma trận tương quan giữa các ngành nghề
# Để làm điều này, chúng ta cần chuyển vị (transpose) DataFrame để mỗi ngành nghề là một cột
correlation_matrix_occupations = occupation_llm_usage.T.corr()

# 4. Vẽ biểu đồ nhiệt của ma trận tương quan
plt.figure(figsize=(14, 12))
sns.heatmap(correlation_matrix_occupations,
            annot=True, # Hiển thị giá trị tương quan trên biểu đồ
            cmap='viridis', # Bảng màu 'viridis' cho độ tương phản tốt
            fmt=".2f", # Định dạng số thập phân
            linewidths=.5, # Độ rộng của các đường phân cách giữa các ô
            cbar_kws={'label': 'Hệ số tương quan'}) # Nhãn cho thanh màu

plt.title('Ma trận tương quan về hành vi sử dụng LLM giữa các Ngành nghề trong ngành CS',
          fontsize=16, pad=20) # Thêm khoảng đệm cho tiêu đề
plt.xticks(rotation=45, ha='right', fontsize=10)
plt.yticks(rotation=0, ha='right', fontsize=10) # xoay nhãn trục y để dễ đọc hơn
plt.tight_layout()
plt.show()

#Liệt kê các cặp ngành nghề có hệ số tương quan cao nhất
correlation_pairs = []
for i in range(len(correlation_matrix_occupations.columns)):
    for j in range(i + 1, len(correlation_matrix_occupations.columns)): # Iterate over upper triangle
        col1 = correlation_matrix_occupations.columns[i]
        col2 = correlation_matrix_occupations.columns[j]
        correlation_value = correlation_matrix_occupations.loc[col1, col2]
        correlation_pairs.append({'Occupation_Pair': f"{col1} - {col2}", 'Correlation': correlation_value})

# Convert to DataFrame and sort by correlation
correlation_df = pd.DataFrame(correlation_pairs)
sorted_correlation_df = correlation_df.sort_values(by='Correlation', ascending=False)

print("Các cặp ngành nghề có hệ số tương quan cao nhất:")
display(sorted_correlation_df.head(10))

"""### **4.1 Đánh giá mức độ mong muốn tự động hóa, lý do (giảm stress, thiếu thời gian) và mức độ tận hưởng công việc.**"""

cs_keywords = ['Software', 'Computer', 'Data', 'Programmer', 'Developer']
cs_automation_df = final_merged_df[final_merged_df['Occupation'].str.contains('|'.join(cs_keywords), na=False)].copy()

# Select relevant columns for this analysis
relevant_automation_cols = [
    'Automation Desire Rating',
    'Enjoyment Rating',
    'Reasons for Automation Desire - Free Time',
    'Reasons for Automation Desire - Stress'
]
cs_automation_df = cs_automation_df[relevant_automation_cols]

# --- 1. Phân tích "Automation Desire Rating" (Mức độ mong muốn tự động hóa) ---
print("\n--- 1. Mức độ mong muốn tự động hóa trong ngành Khoa học máy tính ---")
print(cs_automation_df['Automation Desire Rating'].value_counts().sort_index())
print("\nPhần trăm các mức độ mong muốn tự động hóa:")
print(cs_automation_df['Automation Desire Rating'].value_counts(normalize=True).sort_index().mul(100).round(2))

plt.figure(figsize=(8, 5))
sns.countplot(data=cs_automation_df, x='Automation Desire Rating', palette='viridis', legend=False)
plt.title('Phân phối Mức độ mong muốn tự động hóa', fontsize=14)
plt.xlabel('Mức độ mong muốn tự động hóa (1=Thấp, 5=Cao)', fontsize=12)
plt.ylabel('Số lượng người trả lời', fontsize=12)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

# --- 2. Phân tích "Enjoyment Rating" (Mức độ tận hưởng công việc) ---
print("\n--- 2. Mức độ tận hưởng công việc trong ngành Khoa học máy tính ---")
print(cs_automation_df['Enjoyment Rating'].value_counts().sort_index())
print("\nPhần trăm các mức độ tận hưởng công việc:")
print(cs_automation_df['Enjoyment Rating'].value_counts(normalize=True).sort_index().mul(100).round(2))

plt.figure(figsize=(8, 5))
sns.countplot(data=cs_automation_df, x='Enjoyment Rating', palette='magma', legend=False)
plt.title('Phân phối Mức độ tận hưởng công việc', fontsize=14)
plt.xlabel('Mức độ tận hưởng công việc (1=Thấp, 5=Cao)', fontsize=12)
plt.ylabel('Số lượng người trả lời', fontsize=12)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()


# --- 3. Phân tích các lý do mong muốn tự động hóa (Free Time và Stress) ---
print("\n--- 3. Các lý do mong muốn tự động hóa ---")

# Calculate proportion of respondents who selected 'Free Time' as a reason
free_time_prop = cs_automation_df['Reasons for Automation Desire - Free Time'].mean() * 100
print(f"Tỷ lệ người muốn tự động hóa để có 'Free Time': {free_time_prop:.2f}%")

# Calculate proportion of respondents who selected 'Stress' as a reason
stress_prop = cs_automation_df['Reasons for Automation Desire - Stress'].mean() * 100
print(f"Tỷ lệ người muốn tự động hóa để giảm 'Stress': {stress_prop:.2f}%")

# Visualize reasons
reasons_data = pd.DataFrame({
    'Reason': ['Free Time', 'Stress'],
    'Percentage': [free_time_prop, stress_prop]
})

plt.figure(figsize=(7, 5))
sns.barplot(data=reasons_data, x='Reason', y='Percentage', palette='cividis', legend=False)
plt.title('Tỷ lệ người muốn tự động hóa vì các lý do', fontsize=14)
plt.xlabel('Lý do', fontsize=12)
plt.ylabel('Tỷ lệ (%)', fontsize=12)
plt.ylim(0, 100)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

"""**1. Mức độ mong muốn tự động hóa:**

- Khoảng 9.33% người được hỏi có mức độ mong muốn tự động hóa thấp (Rating 1).
- Khoảng 23.56% ở mức Rating 2.
- Khoảng 26.00% ở mức Rating 3.
- Khoảng 25.33% ở mức Rating 4.
- Khoảng 15.78% có mức độ mong muốn tự động hóa cao nhất (Rating 5).

Biểu đồ "Phân phối Mức độ mong muốn tự động hóa" đã được tạo ra để trực quan hóa những số liệu này, cho thấy phần lớn người làm trong ngành Khoa học Máy tính có mức độ mong muốn tự động hóa từ trung bình đến cao.

**2. Mức độ tận hưởng công việc:**
- Khoảng 15.11% người được hỏi có mức độ tận hưởng công việc thấp (Rating 1).
- Khoảng 23.44% ở mức Rating 2.
- Khoảng 31.33% ở mức Rating 3.
- Khoảng 20.44% ở mức Rating 4.
- Khoảng 9.67% có mức độ tận hưởng công việc cao nhất (Rating 5).

Biểu đồ "Phân phối Mức độ tận hưởng công việc" cũng đã được tạo ra để minh họa sự phân bố này, cho thấy một phân phối tương đối trải rộng nhưng tập trung nhiều nhất ở mức trung bình.

**3. Lý do mong muốn tự động hóa:**
- 48.56% người được hỏi muốn tự động hóa để có 'Free Time' (thời gian rảnh).
- 20.22% người được hỏi muốn tự động hóa để giảm 'Stress'.

Biểu đồ cột "Tỷ lệ người muốn tự động hóa vì các lý do" đã được hiển thị, cho thấy 'Free Time' là động lực chính thúc đẩy mong muốn tự động hóa so với 'Stress'.

# **4.2 Đánh giá của chuyên gia về khả năng AI có thể thay thế/hỗ trợ từng Task cụ thể.**
"""

print("\n--- 4.2 Đánh giá của chuyên gia về khả năng AI có thể thay thế/hỗ trợ từng Task cụ thể ---")

# Filter experts DataFrame for Computer Science occupations
cs_keywords = ['Software', 'Computer', 'Data', 'Programmer', 'Developer']
cs_experts_df = experts[experts['Occupation (O*NET-SOC Title)'].str.contains('|'.join(cs_keywords), na=False)].copy()

# Ensure 'Automation Capacity Rating' is numeric and handle potential NaNs
cs_experts_df['Automation Capacity Rating'] = pd.to_numeric(cs_experts_df['Automation Capacity Rating'], errors='coerce')
cs_experts_df.dropna(subset=['Automation Capacity Rating'], inplace=True)

if cs_experts_df.empty:
    print("Không có dữ liệu chuyên gia về khả năng AI cho các ngành Khoa học Máy tính sau khi lọc.")
else:
    # 1. Overall Distribution of 'Automation Capacity Rating'
    print("\n1. Phân phối chung của 'Automation Capacity Rating' trong các tác vụ CS:")
    print(cs_experts_df['Automation Capacity Rating'].value_counts().sort_index())
    print("\nPhần trăm các mức độ 'Automation Capacity Rating':")
    print(cs_experts_df['Automation Capacity Rating'].value_counts(normalize=True).sort_index().mul(100).round(2))

    plt.figure(figsize=(9, 6))
    sns.countplot(data=cs_experts_df, x='Automation Capacity Rating', palette='Spectral', legend=False)
    plt.title('Phân phối Đánh giá Khả năng Tự động hóa của AI thực hiện tác vụ (trong ngành CS)', fontsize=15)
    plt.xlabel('Automation Capacity Rating (1=Không, 5=Hoàn toàn)', fontsize=12)
    plt.ylabel('Số lượng Đánh giá', fontsize=12)
    plt.grid(axis='y', linestyle='--', alpha=0.7)
    plt.show()

    # 2. Top Tasks where AI is rated highly (e.g., Rating >= 4)
    high_ai_can_do_tasks = cs_experts_df[cs_experts_df['Automation Capacity Rating'] >= 4]
    print("\n2. Các tác vụ được đánh giá cao về khả năng Tự động hóa của AI (Rating >= 4):")
    if not high_ai_can_do_tasks.empty:
        top_tasks_ai_can_do = high_ai_can_do_tasks.groupby(['Occupation (O*NET-SOC Title)', 'Task'])['Automation Capacity Rating'].mean().sort_values(ascending=False)
        print(top_tasks_ai_can_do.head(10).to_string())
    else:
        print("Không có tác vụ nào đạt Rating 4 hoặc 5.")

    # 3. Average 'Automation Capacity Rating' by Occupation
    avg_ai_can_do_by_occupation = cs_experts_df.groupby('Occupation (O*NET-SOC Title)')['Automation Capacity Rating'].mean().sort_values(ascending=False)
    print("\n3. Trung bình 'Automation Capacity Rating' theo từng ngành nghề trong CS:")
    print(avg_ai_can_do_by_occupation.to_string())

    plt.figure(figsize=(12, 7))
    sns.barplot(x=avg_ai_can_do_by_occupation.index, y=avg_ai_can_do_by_occupation.values, palette='coolwarm')
    plt.title('Trung bình Đánh giá Khả năng Tự động hóa của AI thực hiện tác vụ theo Ngành nghề (trong ngành CS)', fontsize=15)
    plt.xlabel('Ngành nghề', fontsize=12)
    plt.ylabel('Trung bình Automation Capacity Rating', fontsize=12)
    plt.xticks(rotation=45, ha='right', fontsize=10)
    plt.ylim(1, 5) # Rating scale
    plt.grid(axis='y', linestyle='--', alpha=0.7)
    plt.tight_layout()
    plt.show()

"""**1. Phân phối chung về mức độ đánh giá khả năng tự động hóa của AI trong ngành Khoa học Máy tính:**

- Chỉ 1.71% tác vụ được đánh giá là AI không thể tự động hóa (Rating 1).
- 15.02% tác vụ được đánh giá ở mức Rating 2 (AI ít có khả năng tự động hóa).
- 33.11% tác vụ nằm ở mức Rating 3 (khả năng tự động hóa trung bình).
- 30.38% tác vụ được đánh giá ở mức Rating 4 (AI có thể tự động hóa cao).
- 19.80% tác vụ được đánh giá là AI hoàn toàn có thể tự động hóa (Rating 5).

Điều này cho thấy phần lớn các tác vụ trong ngành Khoa học Máy tính được các chuyên gia đánh giá là có khả năng được AI tự động hóa ở mức độ trung bình đến cao (khoảng 83.3% ở Rating 3 trở lên).

**2. Các tác vụ được đánh giá cao về khả năng tự động hóa của AI (Rating >= 4):**

Một số tác vụ cụ thể mà AI được đánh giá cao khả năng tự động hóa bao gồm:

- **Lập trình máy tính:** Điều tra xem mạng, máy trạm hoặc thiết bị ngoại vi có phản hồi hướng dẫn của chương trình không; Chuẩn bị biểu đồ và sơ đồ luồng công việc chi tiết và chuyển đổi chúng thành một loạt hướng dẫn được mã hóa bằng ngôn ngữ máy tính.
- **Quản trị viên hệ thống mạng và máy tính:** Cấu hình, giám sát và duy trì các ứng dụng email hoặc phần mềm chống vi-rút.
- **Phân tích và kiểm thử chất lượng phần mềm:** Thực hiện kiểm tra khả năng tương thích của phần mềm, tạo và duy trì cơ sở dữ liệu các lỗi đã biết, lập tài liệu quy trình kiểm thử.
- **Phát triển Web:** Cung cấp mô tả rõ ràng, chi tiết về thông số kỹ thuật trang web và khuyến nghị, thực hiện cải tiến hiệu suất, trả lời các yêu cầu email của người dùng hoặc thiết lập hệ thống tự động để gửi phản hồi.

**3. Trung bình Mức độ đánh giá khả năng tự động hóa của AI theo từng ngành nghề trong ngành Khoa học Máy tính:**

Các ngành nghề có điểm trung bình cao nhất về khả năng tự động hóa của AI bao gồm:

- Nhà phát triển Web (Web Developers): 4.09
- Chuyên gia hỗ trợ người dùng máy tính (Computer User Support Specialists): 3.89
- Lập trình viên máy tính (Computer Programmers): 3.84
- Quản trị viên cơ sở dữ liệu (Database Administrators): 3.80

Trong khi đó, các ngành như Nhà khoa học nghiên cứu máy tính và thông tin (Computer and Information Research Scientists) và Quản lý hệ thống máy tính và thông tin (Computer and Information Systems Managers) có điểm trung bình thấp hơn, cho thấy các tác vụ của họ ít có khả năng được tự động hóa hoàn toàn bởi AI hơn.

Nhìn chung, phân tích này cung cấp cái nhìn chi tiết về các lĩnh vực và tác vụ cụ thể trong Khoa học Máy tính mà AI được kỳ vọng sẽ có tác động đáng kể đến tự động hóa.

# **5. Khuyến nghị AI Agent trong ngành Khoa học máy tính**

Từ các phân tích về nhu cầu tự động hóa, đánh giá của chuyên gia về khả năng AI, hành vi sử dụng LLM hiện tại, tâm lý người dùng và các tác vụ 'điểm đau' trong ngành Khoa học Máy tính, chúng tôi đề xuất các khuyến nghị sau đây cho việc phát triển và triển khai AI Agent:

### **1. Tập trung vào việc tiết kiệm thời gian và tăng hiệu quả công việc**
*   **Khuyến nghị:** Phát triển các AI Agent có khả năng giảm đáng kể thời gian dành cho các tác vụ lặp đi lặp lại, mang tính quy trình hoặc cần nhiều thông tin, từ đó giải phóng thời gian cho các chuyên gia để tập trung vào công việc sáng tạo hoặc chiến lược hơn.
*   **Cơ sở:** Động lực chính cho mong muốn tự động hóa là 'Thời gian rảnh' (48.56%), cao hơn đáng kể so với 'Giảm căng thẳng' (20.22%).
*   **Ví dụ về AI Agent:**
    *   **Agent tạo tài liệu tự động:** Chuyển đổi mã nguồn hoặc thông số kỹ thuật thành tài liệu dự án, tài liệu hướng dẫn sử dụng.
    *   **Agent tổng hợp thông tin:** Trích xuất và tóm tắt thông tin từ các tài liệu kỹ thuật, nghiên cứu, hoặc báo cáo lỗi để hỗ trợ lập trình viên, QA.
    *   **Agent gỡ lỗi sơ bộ:** Thực hiện kiểm tra lỗi cơ bản và gợi ý các giải pháp ban đầu.

### **2. Ưu tiên các lĩnh vực có tiềm năng tự động hóa cao**
*   **Khuyến nghị:** Tập trung phát triển AI Agent cho các tác vụ trong Phát triển Web, Hỗ trợ người dùng máy tính, Lập trình máy tính và Quản trị cơ sở dữ liệu, vì đây là những lĩnh vực được các chuyên gia đánh giá có khả năng tự động hóa cao bởi AI.
*   **Cơ sở:** Các chuyên gia đánh giá cao khả năng tự động hóa của AI trong các ngành này (ví dụ: Web Developers đạt 4.09, Computer Programmers đạt 3.84).
*   **Ví dụ về AI Agent:**
    *   **Agent phát triển Web:** Tự động tạo mã boilerplate (khung code), tối ưu hóa hiệu suất giao diện người dùng/máy chủ, đề xuất cải tiến thiết kế và tự động hóa các phản hồi email khách hàng.
    *   **Agent hỗ trợ người dùng:** Hỗ trợ chẩn đoán ban đầu, cung cấp giải pháp từ cơ sở tri thức, tóm tắt nhật ký lỗi và tài liệu hướng dẫn.
    *   **Agent lập trình:** Hỗ trợ sinh mã, tối ưu hóa mã, tạo unit test và giải thích các đoạn mã phức tạp.

### **3. Thiết kế AI Agent đa năng, hỗ trợ nhiều khía cạnh công việc**
*   **Khuyến nghị:** Xây dựng AI Agent linh hoạt, không chỉ giới hạn ở việc viết code mà còn hỗ trợ các tác vụ quan trọng khác như truy cập thông tin, chỉnh sửa, tạo ý tưởng và phân tích.
*   **Cơ sở:** Dữ liệu sử dụng LLM cho thấy AI được ứng dụng rộng rãi trong truy cập thông tin, chỉnh sửa, tạo ý tưởng và phân tích, không chỉ riêng coding.
*   **Ví dụ về AI Agent:**
    *   **AI Copilot trong IDE:** Cung cấp không chỉ gợi ý code mà còn truy vấn tài liệu, tóm tắt ý tưởng thiết kế và phân tích cấu trúc dự án.
    *   **AI cho phân tích hệ thống:** Phân tích nhật ký hệ thống (logs), dự đoán lỗi và đề xuất giải pháp tối ưu.

### **4. Xây dựng AI Agent thân thiện, giảm thiểu lo ngại của người dùng**
*   **Khuyến nghị:** Thiết kế AI Agent với giao diện trực quan, làm nổi bật lợi ích rõ ràng và tập trung vào vai trò hỗ trợ thay vì thay thế. Cung cấp đào tạo và hỗ trợ tích hợp để khuyến khích sử dụng thường xuyên.
*   **Cơ sở:** Người dùng AI thường xuyên có xu hướng ít lo ngại hơn về AI gây ra 'đau khổ' so với người không dùng. AI được đánh giá cao trong việc giảm bớt công việc tẻ nhạt.
*   **Ví dụ về AI Agent:**
    *   **AI Agent có khả năng giải thích (Explainable AI):** Cung cấp lý do đằng sau các đề xuất hoặc quyết định của AI để xây dựng lòng tin.
    *   **AI Agent hợp tác:** Cho phép người dùng kiểm soát và hiệu chỉnh kết quả của AI, hoạt động như một “người đồng hành” hơn là một công cụ tự động hoàn toàn.

### **5. Giải quyết các tác vụ 'điểm đau' (Pain-Point Tasks) và tăng cường khả năng giải quyết vấn đề**
*   **Khuyến nghị:** Phát triển AI Agent nhằm trực tiếp giải quyết các tác vụ có tần suất cao, tầm quan trọng lớn, và có tính chất lặp lại hoặc liên quan đến việc xử lý thông tin, ghi chép. Các tác vụ này thường là nguyên nhân gây ra 'điểm đau' cho người lao động.
*   **Cơ sở:** Phân tích tác vụ gốc chỉ ra rằng các tác vụ như đọc tài liệu kỹ thuật, chẩn đoán sự cố máy tính, ghi lại lỗi phần mềm, và cài đặt/duy trì phần mềm kiểm thử là những tác vụ thường xuyên và quan trọng.
*   **Ví dụ về AI Agent:**
    *   **Agent Hỗ trợ Chẩn đoán & Xử lý sự cố:** AI Agent có khả năng phân tích nhật ký (logs), tài liệu kỹ thuật và triệu chứng lỗi để đề xuất các giải pháp chẩn đoán và xử lý sự cố ban đầu, đặc biệt hữu ích cho các chuyên gia hỗ trợ người dùng máy tính.
    *   **Agent Quản lý lỗi & Tài liệu:** Tự động hóa việc ghi nhận, phân loại và theo dõi lỗi phần mềm, cũng như tạo và cập nhật tài liệu kiểm thử, giúp giảm gánh nặng cho các nhà phân tích và kiểm thử chất lượng phần mềm.
    *   **Agent Cập nhật Kiến thức Tự động:** Giám sát và tóm tắt các bản cập nhật công nghệ mới, các thay đổi trong quy trình hoặc phần mềm, giúp các chuyên gia luôn nắm bắt thông tin mà không cần dành quá nhiều thời gian cho việc đọc thủ công.
"""